apiVersion: v1
kind: Secret
metadata:
  name: finflow-secrets
  namespace: finflow
type: Opaque
data:
  # Base64 encoded MongoDB Atlas URI
  MONGO_URI: bW9uZ29kYitzcnY6Ly9yZWRkeXN1bWl0aDM1X2RiX3VzZXI6U3VtaXRoJTQwOTAxQHRyYWNrZXIuYjZkcjRraS5tb25nb2RiLm5ldC9leHBlbnNldHJhY2tlcj9yZXRyeVdyaXRlcz10cnVlJnc9bWFqb3JpdHk=
  # Base64 encoded JWT secret key
  JWT_SECRET: MThkNDAyMmJhMmM1OWI3NzI3ODk3YmU4YTg2OWM5ZmY0ODMyNmI2OGY3YzJmOTJlZGZjM2RiMWVkYjEzNTgwNw==
